use_frameworks!

# for development https://github.com/CocoaPods/CocoaPods/pull/5254
install! 'cocoapods',
  :share_schemes_for_development_pods => true

target 'TYTumblrHUD_Example' do
  pod 'TYTumblrHUD', :path => '../'

  target 'TYTumblrHUD_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
